### ISSUE TITLE
Documentation is built, but web pages generated raises a lot of Javascript errors

### ISSUE THREAD

**Issue by jlandercy** [pradyunsg/furo#65]
**Describe the bug**

I just discover your Sphinx Theme and I am facing some JavaScript errors.
If I roll back theme to alabaster (`html_theme = 'alabaster'`), everything runs fine.
I suspect it is a JavaScript issue with CDN library (see screenshots for error logs).

The documentation builds when issuing `make html`, but the resulting website is buggy no index or search is available, even `index.html` raises error.

**To Reproduce**
Steps to reproduce the behaviour:

 - Clone this [version](https://github.com/jlandercy/newproject/commit/9207dab6a32ce448129140b16c978ed7c36a1c5e);
 - Check `html_theme = 'furo'` is the actual Sphinx Theme in `conf.py`;
 - Create documentation by issuing `make html`;
 - Visit the website: `index.html`, `search.html` and `genindex.html` raises JS errors.

**Expected behaviour**

I would expect to have a working documentation as I do with alabaster (rollback compiles and works).
I would like to go deeper with Furo because I like it's minimalistic, clean and sharp looks (layout, code highlight, etc.).
If this bug can be solved, I think it will be my default theme for all my docs.

I think it might be a soft bug, maybe a breaking change somewhere in the JavaScript pipeline...
Let me know if I can help either way.

**Screenshots**

I copy paste some outputs of browser terminal, I think it is better than screenshots.

When loading `index.html` I have those errors, but the HTML is fine:

```
Uncaught ReferenceError: Gumshoe is not defined
    setupScrollSpy main.js:76
    setup main.js:90
    main main.js:99
    EventListener.handleEvent* main.js:102
main.js:76
Uncaught Error: Mismatched anonymous define() module: function(){return t(e)}
http://requirejs.org/docs/errors.html#mismatch
    makeError https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js:1
    v https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js:1
    o https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js:1
    setTimeout handler*req.nextTick< https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js:1
    o https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js:1
    requirejs https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js:1
    <anonymous> https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js:1
    <anonymous> https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js:1
```

If I want to get any index, then I got blank page (because there are dynamically generatde) with those errors:

```
Uncaught Error: Mismatched anonymous define() module: function(){return t(e)}
http://requirejs.org/docs/errors.html#mismatch
    makeError https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js:1
    v https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js:1
    o https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js:1
    setTimeout handler*req.nextTick< https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js:1
    o https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js:1
    requirejs https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js:1
    <anonymous> https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js:1
    <anonymous> https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js:1
```

Search bar does not work, it loops forever:

```
Uncaught Error: Mismatched anonymous define() module: function(){return t(e)}
http://requirejs.org/docs/errors.html#mismatch
    makeError https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js:1
    v https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js:1
    o https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js:1
    setTimeout handler*req.nextTick< https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js:1
    o https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js:1
    requirejs https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js:1
    <anonymous> https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js:1
    <anonymous> https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js:1
require.min.js:1:1067
jQuery.Deferred exception: Stemmer is not defined query@file:///C:/Users/jlanderc/PycharmProjects/newproject/newproject-docs/build/html/_static/searchtools.js:158:19
performSearch@file:///C:/Users/jlanderc/PycharmProjects/newproject/newproject-docs/build/html/_static/searchtools.js:146:12
init@file:///C:/Users/jlanderc/PycharmProjects/newproject/newproject-docs/build/html/_static/searchtools.js:79:16
@file:///C:/Users/jlanderc/PycharmProjects/newproject/newproject-docs/build/html/_static/searchtools.js:513:10
e@file:///C:/Users/jlanderc/PycharmProjects/newproject/newproject-docs/build/html/_static/jquery.js:2:30005
l/</t<@file:///C:/Users/jlanderc/PycharmProjects/newproject/newproject-docs/build/html/_static/jquery.js:2:30307
setTimeout handler*l/<@file:///C:/Users/jlanderc/PycharmProjects/newproject/newproject-docs/build/html/_static/jquery.js:2:30516
c@file:///C:/Users/jlanderc/PycharmProjects/newproject/newproject-docs/build/html/_static/jquery.js:2:28294
fireWith@file:///C:/Users/jlanderc/PycharmProjects/newproject/newproject-docs/build/html/_static/jquery.js:2:29039
fire@file:///C:/Users/jlanderc/PycharmProjects/newproject/newproject-docs/build/html/_static/jquery.js:2:29075
c@file:///C:/Users/jlanderc/PycharmProjects/newproject/newproject-docs/build/html/_static/jquery.js:2:28294
fireWith@file:///C:/Users/jlanderc/PycharmProjects/newproject/newproject-docs/build/html/_static/jquery.js:2:29039
ready@file:///C:/Users/jlanderc/PycharmProjects/newproject/newproject-docs/build/html/_static/jquery.js:2:32012
setTimeout handler*@file:///C:/Users/jlanderc/PycharmProjects/newproject/newproject-docs/build/html/_static/jquery.js:2:32137
@file:///C:/Users/jlanderc/PycharmProjects/newproject/newproject-docs/build/html/_static/jquery.js:2:220
@file:///C:/Users/jlanderc/PycharmProjects/newproject/newproject-docs/build/html/_static/jquery.js:2:225
 undefined jquery.js:2:31560
Uncaught ReferenceError: Stemmer is not defined
    query file:///C:/Users/jlanderc/PycharmProjects/newproject/newproject-docs/build/html/_static/searchtools.js:158
    performSearch file:///C:/Users/jlanderc/PycharmProjects/newproject/newproject-docs/build/html/_static/searchtools.js:146
    init file:///C:/Users/jlanderc/PycharmProjects/newproject/newproject-docs/build/html/_static/searchtools.js:79
    <anonymous> file:///C:/Users/jlanderc/PycharmProjects/newproject/newproject-docs/build/html/_static/searchtools.js:513
    jQuery 12
```

**Desktop (please complete the following information):**

- OS: Win10 up-to-date
- Browser: Firefox 84.0.1 (64 bits) up-to-date, Edge 87.0.664.66 (64 bits)
- Version: `furo==2020.12.9b21` (by the way this version name makes PyCharm raising a false negative error about availability of the package in the virtual environment)

**Additional context**

Thank you for the job, looks very promising!

**Comment by pradyunsg** [comment]
This was fixed in #58. It'll be a part of the next release.

**Comment by jlandercy** [comment]
Thank you for this fast release, index pages are now rendered.
Anyway I just want to warn you @pradyunsg  about an existing errors that still appears on every page:

```
Uncaught ReferenceError: Gumshoe is not defined
    setupScrollSpy main.js:76
    setup main.js:90
    main main.js:99
    EventListener.handleEvent* main.js:102
main.js:76
Uncaught Error: Mismatched anonymous define() module: function(){return t(e)}
http://requirejs.org/docs/errors.html#mismatch
    makeError https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js:1
    v https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js:1
    o https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js:1
    setTimeout handler*req.nextTick< https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js:1
    o https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js:1
    requirejs https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js:1
    <anonymous> https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js:1
    <anonymous> https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js:1
```

Nice work.
Best regards,

Jean
