### ISSUE TITLE
Error when using JSON builder

### ISSUE THREAD

**Issue by carltongibson** [pradyunsg/furo#89]
Hi. Thanks for the lovely project! 

The `furo` theme is not compatible currently with the json builder. 

1. Create a project and enable the `furo` theme. 
2. `make html` (Observe no problem)
3. `make json` (Error: see below)
4. Comment out `furo` theme 
5. `make json` (Observe no problem)

At step three, the end of the traceback is: 

```
  File "/env/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 360, in build
    self.write(docnames, list(updated_docnames), method)
  File "/env/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 534, in write
    self._write_serial(sorted(docnames))
  File "/env/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 544, in _write_serial
    self.write_doc(docname, doctree)
  File "/env/lib/python3.8/site-packages/sphinx/builders/html/__init__.py", line 611, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "/env/lib/python3.8/site-packages/sphinxcontrib/serializinghtml/__init__.py", line 104, in handle_page
    self.dump_context(ctx, outfilename)
  File "/env/lib/python3.8/site-packages/sphinxcontrib/serializinghtml/__init__.py", line 79, in dump_context
    self.implementation.dump(context, ft, *self.additional_dump_args)
  File "/env/lib/python3.8/site-packages/sphinxcontrib/serializinghtml/jsonimpl.py", line 31, in dump
    json.dump(obj, fp, *args, **kwds)
  File "/Users/carlton/.pyenv/versions/3.8.3/lib/python3.8/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/Users/carlton/.pyenv/versions/3.8.3/lib/python3.8/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/Users/carlton/.pyenv/versions/3.8.3/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Users/carlton/.pyenv/versions/3.8.3/lib/python3.8/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/env/lib/python3.8/site-packages/sphinxcontrib/serializinghtml/jsonimpl.py", line 25, in default
    return super().default(obj)
  File "/.pyenv/versions/3.8.3/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _lru_cache_wrapper is not JSON serializable
```

**Expected behavior**
The JSON builder should succeed. 

- Version: `furo==2021.2.21b25`

**Comment by pradyunsg** [comment]
Ooh. Fun. :)

**Comment by pradyunsg** [comment]
Should be fixed by 409b09041688f27e1908bcdd010c71c9e59f42c9. :)

**Comment by carltongibson** [comment]
@pradyunsg That was quick. 😀

I'm off now. I will give it a run when I'm back at the computer. Thanks!

**Comment by carltongibson** [comment]
Hi @pradyunsg — amusingly the packing setup you have going on here is so advanced I couldn't get it running in the time I can allocate to this, so I couldn't test the fix yet. (Still occurs with the latest tag, but the commit is not in that...) 

I wanted to just `pip install git+...` but that failed. I then cloned and wanted to do it locally with `pip install -e .` but we don't have a `setup.py`. 

Grrr. OK. Look into `nox` as per the docs you have.  

Adjusted the `docs` command to use the json builder but got an error: 

```
(furo) furo ((1eeb2e1...))$ nox -s docs  # This is 409b090^
nox > Running session docs
nox > Re-using existing virtual environment at .nox/docs.
nox > Program gulp not found.   # I did run npm install as per instructions. 
nox > Session docs failed.
```

At this point I'm like Argh! — this is going to take more than I can give it right now. 
Wasn't then able verify the fix my end. Sorry about that.

**Comment by pradyunsg** [comment]
No worries. I’ll cut a release today, you can try that! :)

**Comment by carltongibson** [comment]
Super. Thanks!

**Comment by pradyunsg** [comment]
Released in beta27. :)

**Comment by carltongibson** [comment]
Hi @pradyunsg — thanks for that, I was able to update. 

Getting a new error now... 🤔

```
Extension error (furo):
Handler <function _html_page_context at 0x1086c0c10> for event 'html-page-context' threw an exception (exception: 'style')
make: *** [json] Error 2
```

I'll sit down and go through your setup when I have a cycle so I can use the development version locally. I should then be able to offer better input. (I suspect I'm the only person trying to do this. 🙂)

**Comment by pradyunsg** [comment]
https://pradyunsg.me/furo/contributing/workflow/#installing-directly-from-the-repository-development

This should help. :)

**Comment by pradyunsg** [comment]
I've just pushed 642bd53a7d6b7c3bb969e04f8e9050320668bba5, which seems to fix it for me locally. :)

**Comment by carltongibson** [comment]
Super. I'll give it another pass later on. Thanks for the help.

**Comment by pradyunsg** [comment]
It's in beta28 now. :)

**Comment by carltongibson** [comment]
Hi @pradyunsg — thanks for this. Just confirming that `make json` can succeed with beta28. 💃

Keep up the good work! 👍
